# Generated by Django 4.1.4 on 2023-01-14 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0002_alter_comments_article_alter_comments_commentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsprediction',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_prediction', to=settings.AUTH_USER_MODEL),
        ),
    ]
