# Generated by Django 4.1.4 on 2023-01-14 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0003_alter_newsprediction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsprediction',
            name='user',
        ),
        migrations.AddField(
            model_name='newsprediction',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
