# Generated by Django 4.1.4 on 2023-01-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0004_remove_newsprediction_user_newsprediction_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('pos', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('neg', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('nue', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('article', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analysis', to='fakenews.newsprediction')),
            ],
        ),
        migrations.CreateModel(
            name='Linguistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('uppercase_count', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('lowercase_count', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('num_counts', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('at_count', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('question_count', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('slash_count', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('hashtag_count', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('word_count', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('char_count', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('sentence_count', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('avg_word_length', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('avg_sentence_length', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('article', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linguistic_analysis', to='fakenews.newsprediction')),
            ],
        ),
    ]
