# Generated by Django 4.1.4 on 2023-01-16 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0005_sentiment_linguistic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentiment',
            old_name='neg',
            new_name='sentiment_neg',
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='nue',
            new_name='sentiment_nue',
        ),
        migrations.RenameField(
            model_name='sentiment',
            old_name='pos',
            new_name='sentiment_pos',
        ),
        migrations.RemoveField(
            model_name='linguistic',
            name='article',
        ),
        migrations.RemoveField(
            model_name='sentiment',
            name='article',
        ),
        migrations.AlterField(
            model_name='newsprediction',
            name='linguistic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linguistic_analysis', to='fakenews.linguistic'),
        ),
        migrations.AlterField(
            model_name='newsprediction',
            name='sentiment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analysis', to='fakenews.sentiment'),
        ),
    ]
