# Generated by Django 4.1.4 on 2023-01-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0006_rename_neg_sentiment_sentiment_neg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='sentiment_nuetral',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
    ]
