# Generated by Django 4.1.4 on 2023-01-16 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0007_sentiment_sentiment_nuetral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiment',
            name='sentiment_nue',
        ),
    ]
