# Generated by Django 4.1.4 on 2023-05-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0009_user_b_day_user_contact_no_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence', models.CharField(blank=True, max_length=500, null=True)),
                ('news_prediction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='fakenews.newsprediction')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(blank=True, max_length=500, null=True)),
                ('sentence', models.CharField(blank=True, max_length=500, null=True)),
                ('manual_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='fakenews.manualcheck')),
            ],
        ),
    ]
